## 1.1 育种目标性状

育种目标是指在罗氏沼虾育种计划中，将要进行遗传改良的性状。育种目标性状一般符合以下3个条件：1）.必须是利用现有的仪器可测量的；2）.获取性状数据的测量成本应当较低；3）.性状在遗传上表现为加性效应。从理论上来说，育种目标应包括所有重要的经济性状。借鉴其他物种的育种经验，根据罗氏沼虾的实际育种需求，选择收获体重和存活2个性状作为目标性状。

## 1.2 基础群体

基础群体遗传变异的丰富度，决定着罗氏沼虾育种计划是否能够成功。罗氏沼虾作为一个引进种，国内种质资源缺乏。限于现有条件，本育种计划的奠基者群体为：
2015年引入：MP-2014年家系混合群体；DP-2015年扩繁群体；MN-缅甸群体；BD-孟加拉群体；T1-泰国正大群体

2016年引入：T2-泰国正大群体。

## 1.3 家系生产

单独建立家系，一方面是为了记录个体的系谱，另外有许多重要的性状，譬如存活率和抗病性等，不能在候选亲本上进行测试，但是可以通过收集家系中的同胞个体的测试数据来间接进行评估。为保证罗氏沼虾育种计划的可持续性，每个世代构建全同胞家系应不少于150个。

2018年通过脱卵消毒，共构建家系142个；从第一个家系变苗（2018.3.25）到最后一个（2018.4.24）相差30天。淘汰暂养期存活率较低家系，保留129个家系。2018年6月25日开始打标记下塘养殖，每个家系挑选300尾个体大的虾进行标记，平均分在两个测试土池（P10、P11）养殖。2018年养殖测试密度提高到了每平方米9尾以上。

### 1.3.1	亲虾越冬

从上一年10月起捕核心群体至第二年2月配种前，亲虾需要在温室经过4-5个月的越冬期管理。越冬期间，一方面需要尽可能保证亲虾的越冬成活率以减少优良亲虾的损失，另一方面需要保证亲虾越冬期的营养需求，从而增强亲虾的体质，确保受精卵的质量和数量；保持亲虾养殖的水质稳定，促进雌虾性腺同步发育，从而缩短家系间由于育苗时间不同引起的误差。

### 1.3.2	亲虾交配

配种亲虾源自上一年体重育种值排序靠前的家系；待搭配个体间的亲缘关系设置为亲缘系数上限制；家系内选择高育种值个体，家系间随机搭配；每个家系贡献同等入选个体数量，一般不超过3尾；雌雄性别比例为4：1，雌虾均来自不同家系。配种流程为从个体网箱内取虾，核对颜色及雌雄，按交配组号集中暂养，消毒，入配种池。备份雄虾转移至新的个体网箱内养殖，重新记录个体编号。实验表明使用小型水泥池（3平方米）作为罗氏沼虾配种池，可以促进亲虾性腺发育，提高亲虾产卵同步性，减少雌虾脱卵率及亲虾死亡率。

### 1.3.3	家系构建与幼体培育

2018年构建的所有家系都经过脱卵消毒。配种后定期检查每个交配池抱卵虾情况，发现虾卵颜色变灰，把灰卵虾抓出，单独放入含5‰胰蛋白酶溶液的小桶中，浸泡约10分钟后，抓住虾头胸甲部分，在胰蛋白酶溶液中来回甩动，使卵散落在溶液中。待虾腹部卵粒全部脱落后，用60目的纱绢网将卵粒收集，并用清水冲洗，将卵上的胰蛋白酶冲洗干净，然后连同纱绢网把卵粒浸没在75%的酒精中消毒25秒；然后再用清水冲洗卵粒，最后把所有卵粒放入预先加有盐度7‰半咸水的120L白桶内，爆气孵化。

每天早上检查孵化桶的孵化情况，发现幼体即用60目的纱绢网将幼体移出，计数2000尾（第1次数量标准化）放入已预先加入50L盐度为14‰半咸水的白桶内进行培育，剩余幼体移入扩繁培育池。前一周投喂5个/ml密度的卤虫无节幼体，第8天左右开始增加投喂人工制作的蛋羹。当80%以上幼体变态成仔虾时，分二次将海水盐度淡化至3‰以内。淡化后第2天上午，用60目纱绢网将仔虾捞出。计数600尾（第2次数量标准化）移入家系虾苗暂养车间的3平方米的暂养池内进行中间培育。

### 1.3.4	家系幼体中间培育

仔虾淡化后的第2天，每个家系随机准确计数600尾活力强的仔虾分别放入3平方米的水泥池中养殖，经过30天左右的养殖，仔虾可生长至体长2.5cm，达到标记规格。仔虾培育期间投喂虾片及罗氏沼虾配合饲料。

### 1.3.5	病原检测

为确保所有家系不带特定的几种病原，对每个家系脱卵消毒后的卵粒、培育期间的幼体和第二次数量标准化前的仔虾分别取样检测，检测阴沟肠杆菌、柠檬酸杆菌、嗜水气单胞菌、产气肠杆菌、诺达病毒、诺谛病毒和双顺反子病毒等病源，淘汰检测呈阳性的家系。

## 1.4 家系和个体标记

将所有家系的测试个体，放入相同的环境中测试，能够降低环境效应，增加育种值估计的准确度。因此，需要对家系测试个体进行标记。此外，为了追踪测试个体和候选育种亲本的系谱，也需要对个体进行标记。本育种计划采用VIE荧光染料和箱笼法对罗氏沼虾进行家系和个体标记。

### 1.4.1	家系标记

应用“可视嵌入性橡胶标志” (visible implant elastomer, VIE)作为家系标记方法，标记材料选用美国NMT公司生产5种荧光颜料（粉、红、橙、黄、绿）和一种非荧光染料（蓝）。在仔虾的第6腹节处选取4个部位中的2个位置进行VIE注射，每个家系用不同的颜色组合进行标记。

### 1.4.2	个体标记

虾类的个体标记目前常用的是眼标（eye tag）。如在中国对虾上，用眼标进行个体标记非常理想，但在罗氏沼虾上，因其眼柄粗短且呈锥形，用眼标标记时，眼标容易脱落。本育种计划采用“个体编号箱笼养殖方法”标记罗氏沼虾候选育种亲本。采用网箱做成的笼格（简称箱笼），单独养殖罗氏沼虾个体，并在箱笼上方挂一有编码的个体标签，以示区分不同个体，有多少个体就做多少箱笼，其个体的标记率和可读率均为100%。经120天的箱笼养殖，其成活率达91.5%。

## 1.5 目标性状测试
2018年6月25日开始对129个家系进行标记VIE，每个家系挑选300尾，测量平均体重，平分在两个养殖测试塘，每个家系每个池塘放养150尾虾，总放苗密度约为每平方米9-10尾虾。10月2日开始起捕，两个塘中的虾全部移入温室暂养。对129个家系的所有个体进行标记颜色读取、体长、体重等性状测量，超过平均体重，且健康完整的个体装入笼子并编号。
2018年罗氏沼虾在2个池塘中测试，面积分别为：P10-2133 平方米; P11-2000 平方米。相比于2017年，2018年测试成活率大幅度提高，62%-68%之间。具体养殖管理信息见下表。

## 1.6 遗传参数和育种值预测


遗传参数（遗传力和遗传相关等）是评估育种目标性状是否具有选择潜力，制定合适的选择策略以及估计育种值等工作必须的基础参数。在罗氏沼虾育种计划中，追踪并建立个体的系谱资料信息，充分利用个体所有的亲缘关系和性能资料；针对生长性状，选择个体动物模型，针对存活性状，选择阈值模型，考虑世代、性别、池塘号、家系等固定和随机因素，建立育种目标性状的混合模型方程；利用REML方法迭代计算选择性状的表型方差、遗传方差、遗传协方差等方差组分，估计性状的遗传参数如遗传力，性状间的遗传相关等，建立遗传参数精确评估模型。

利用ssGBLUP（single step Best linear unbiased prediction）方法估计生长和存活性状的育种值。ssGBLUP方法能够结合亲本的高通量SNP数据校正育种核心群个体间的亲缘关系，同时综合利用各类亲属的测定成绩来综合估计个体育种值，从而明显提高选择的准确度，特别是对于存活率等低遗传力性状，效果更为明显。收获体重育种值估计模型主要包括世代、性别、测试池塘等固定效应，个体加性遗传效应和共同环境效应2个随机效应。存活率育种值估计模型主要包括世代和测试池塘2个固定个效应，个体加性遗传效应和共同环境效应2个随机效应。

## 1.7 遗传进展预测

在本育种计划中通过两种方式估计遗传进展，实现遗传进展和预测遗传进展。实现遗传进展，通过计算当前世代对照组和选择组2个群体的最小二乘均值获得。计算实现遗传进展，需要在育种核心群设置对照群，该对照群父母本育种值处于上一代选择群体所有个体育种值中间水平。计算预测遗传进展，需要对多个世代生长和存活测试数据合并估计育种值，然后计算不同世代选择群育种值平均值的差值。

## 1.8 综合选择指数制定

生长速率和池塘存活率为重要的经济性状，因此包括进了罗氏沼虾的育种目标中。多个性状同时选择，可以提高育种效率，同时避免相关性状的重要种质资源被淘汰。将多个性状的育种值合并一个综合选择指数，据此对家系和个体进行淘汰，选择高选择指数家系和个体作为留种亲本。抗逆已经发展成为罗氏沼虾一个重要的性状，因此将收获体重和养殖存活率的权重设置为70和30。在选择家系进行扩繁时，将收获体重和养殖存活率设置为同等重要，选择优秀家系进行多级扩繁。

## 1.9 选择策略

育种选择方法依赖于罗氏沼虾的生物学特性和育种目标性状。不同的选择方法，采用不同的信息来源估计个体的育种值。
罗氏沼虾遗传评估信息来源主要包括：个体信息和家系同胞信息。


## 1.10 配种方案制定

一个高效合理的配种方案，在保持低近交率的同时，能够保证育种项目遗传进展的可持续性。在罗氏沼虾育种项目中，制定交配方案主要是考虑以下几个原则：近交系数和选择指数，在控制近交的情况下，实现遗传进展最大化。在本项目中，基于最佳遗传贡献理论，平衡近交水平和遗传进展，制定优化配种方案。 